// <auto-generated />
namespace Hotel_Alumnos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agrega_descripcion_habitacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agrega_descripcion_habitacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202310040058087_agrega_descripcion_habitacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
