// <auto-generated />
namespace Hotel_Alumnos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class agrega_tabla_Huespedes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agrega_tabla_Huespedes));
        
        string IMigrationMetadata.Id
        {
            get { return "202309262344172_agrega_tabla_Huespedes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
