// <auto-generated />
namespace Hotel_Alumnos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class elimino_fechas_del_modelo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(elimino_fechas_del_modelo));
        
        string IMigrationMetadata.Id
        {
            get { return "202310032301203_elimino_fechas_del_modelo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
