// <auto-generated />
namespace Hotel_Alumnos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregar_tabla_TiposDeHabitacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregar_tabla_TiposDeHabitacion));
        
        string IMigrationMetadata.Id
        {
            get { return "202309282218364_agregar_tabla_TiposDeHabitacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
