// <auto-generated />
namespace Hotel_Alumnos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class elimina_tabla_reservas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(elimina_tabla_reservas));
        
        string IMigrationMetadata.Id
        {
            get { return "202310032253376_elimina_tabla_reservas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
