// <auto-generated />
namespace Hotel_Alumnos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class agrega_Excursion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agrega_Excursion));
        
        string IMigrationMetadata.Id
        {
            get { return "202309262324577_agrega_Excursion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
